server:
  port: 8090

spring:
  application:
    name: simulation

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:8081

      client:
        registration:
          gateway-client:
            provider: auth-provider
            client-id: simulation-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          auth-provider:
            token-uri: http://auth:8081/oauth2/token

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085   # adjust if needed
      specific.protobuf.value.type: com.dtcc.simulation.proto.TradeEventOuterClass$TradeEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer

    listener:
      ack-mode: record

  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    driver-class-name: org.postgresql.Driver
    username: pms
    password: pms

  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    trade-topic: trade-events

  rabbitmq:
    stream:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_STREAM_PORT:5552}
      name: ${RABBITMQ_STREAM_NAME:trade-stream}

portfolio:
  service:
    url: http://portfolio-service:8095   # âœ… FIXED

logging:
  level:
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.server.resource: DEBUG
