server:
    port: 8090
spring:
  application:
    name: simulation

  kafka:
    bootstrap-servers: localhost:9092

    properties:
      schema.registry.url: http://localhost:8081
      specific.protobuf.value.type: com.dtcc.simulation.proto.TradeEventOuterClass$TradeEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer

    listener:
      ack-mode: record

  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    driverClassName: org.postgresql.Driver
    username: pms
    password: pms

  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    trade-topic: trade-events
  rabbitmq:
    stream:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_STREAM_PORT:5552}
      name: ${RABBITMQ_STREAM_NAME:trade-stream}

portfolio:
  service:
    url: http://localhost:8080/simulation


