spring:
  application:
    name: simulation

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    initialization-mode: never

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

fmp:
  api:
    key: "tLsLKxYqOgUWPEtJ3aJtT6RGmf3PfiVU"
